try:
    import pytest
    fixture = pytest.fixture
except ImportError:
    def fixture(func):
        return func

import numpy as np

from src.adapters.cognitive.topic_clustering_adapter import TopicClusteringAdapter
from src.domain.clustering.abstractions import (
    KnowledgeGapReport,
    TopicClusteringRequest,
    TopicClusteringResponse,
)


@fixture
def clustering_adapter():
    return TopicClusteringAdapter()


def test_empty_collection_clustering(clustering_adapter):
    """Verify empty chunk list returns clean empty response without error."""
    res = clustering_adapter.cluster_chunks(
        tenant_id="tenant-test-1",
        chunk_ids=[],
        chunk_texts=[],
        embeddings=[],
        request=TopicClusteringRequest(),
    )

    assert isinstance(res, TopicClusteringResponse)
    assert res.total_chunks == 0
    assert res.total_clusters == 0
    assert res.topics == []
    assert res.outlier_chunk_count == 0


def test_small_collection_single_topic_fallback(clustering_adapter):
    """Verify small collections (< 4 chunks) form a single coherent topic."""
    chunk_ids = ["c1", "c2"]
    chunk_texts = [
        "Payment invoices and checkout billing cycles.",
        "Monthly invoices and transaction receipts.",
    ]
    # Synthetic 2D/3D embeddings close together
    embeddings = [[0.8, 0.2, 0.1], [0.85, 0.22, 0.08]]

    res = clustering_adapter.cluster_chunks(
        tenant_id="tenant-test-2",
        chunk_ids=chunk_ids,
        chunk_texts=chunk_texts,
        embeddings=embeddings,
        request=TopicClusteringRequest(),
    )

    assert res.total_chunks == 2
    assert res.total_clusters == 1
    assert len(res.topics) == 1
    topic = res.topics[0]
    assert topic.topic_id == 0
    assert topic.chunk_count == 2
    assert "invoice" in " ".join(topic.keywords).lower() or "payment" in " ".join(topic.keywords).lower()


def test_multi_cluster_c_tfidf_separation(clustering_adapter):
    """Verify distinct semantic clusters (Auth vs Payments) are partitioned and labeled correctly."""
    # Cluster A: Authentication / JWT / Tokens (4 chunks)
    auth_texts = [
        "User login authentication using JWT tokens and OAuth PKCE flow.",
        "Session authentication tokens expire after 7 days.",
        "Secure password hashing and multi-factor authentication login.",
        "Authorization headers pass the Bearer JWT token to API gateway.",
    ]
    auth_vecs = [[0.9 + np.random.normal(0, 0.02), 0.1, 0.0] for _ in range(4)]

    # Cluster B: Invoicing / Stripe / Payments (4 chunks)
    pay_texts = [
        "Monthly subscription invoices generated by Stripe billing.",
        "Tax invoices include GST numbers and payment receipts.",
        "Escrow deposit payments are captured on checkout sign-off.",
        "Refund policies and billing transaction ledgers.",
    ]
    pay_vecs = [[0.1, 0.9 + np.random.normal(0, 0.02), 0.0] for _ in range(4)]

    chunk_ids = [f"auth_{i}" for i in range(4)] + [f"pay_{i}" for i in range(4)]
    chunk_texts = auth_texts + pay_texts
    embeddings = auth_vecs + pay_vecs

    res = clustering_adapter.cluster_chunks(
        tenant_id="tenant-test-3",
        chunk_ids=chunk_ids,
        chunk_texts=chunk_texts,
        embeddings=embeddings,
        request=TopicClusteringRequest(min_cluster_size=2, method="kmeans", top_k_keywords=4),
    )

    assert res.total_chunks == 8
    assert res.total_clusters >= 2
    assert len(res.topics) >= 2

    # Verify keyword distinctiveness across topics
    all_keywords = " ".join([" ".join(t.keywords) for t in res.topics]).lower()
    assert "authentication" in all_keywords or "token" in all_keywords or "login" in all_keywords
    assert "invoice" in all_keywords or "payment" in all_keywords or "billing" in all_keywords


def test_knowledge_gap_detection(clustering_adapter):
    """Verify knowledge gap report identifies orphaned chunks and computes coverage density."""
    chunk_ids = ["c1", "c2", "c3", "orphan_1"]
    chunk_texts = [
        "OAuth authentication protocol.",
        "JWT token validation workflow.",
        "User session token management.",
        "Completely isolated obscure paragraph with no context.",
    ]
    embeddings = [
        [0.9, 0.1, 0.0],
        [0.92, 0.08, 0.01],
        [0.88, 0.12, 0.0],
        [0.0, 0.0, 0.99],  # Outlier
    ]

    clustering_res = clustering_adapter.cluster_chunks(
        tenant_id="tenant-gap-1",
        chunk_ids=chunk_ids,
        chunk_texts=chunk_texts,
        embeddings=embeddings,
        request=TopicClusteringRequest(min_cluster_size=2, method="hdbscan"),
    )

    chunk_text_dict = dict(zip(chunk_ids, chunk_texts, strict=False))
    gap_report = clustering_adapter.analyze_knowledge_gaps(
        tenant_id="tenant-gap-1",
        clustering_result=clustering_res,
        chunk_texts=chunk_text_dict,
    )

    assert isinstance(gap_report, KnowledgeGapReport)
    assert gap_report.total_chunks == 4
    assert 0.0 <= gap_report.knowledge_coverage_score <= 1.0
    assert len(gap_report.recommendations) > 0


if __name__ == "__main__":
    adapter = TopicClusteringAdapter()
    print("Testing empty collection clustering...")
    test_empty_collection_clustering(adapter)
    print("✓ Empty collection test passed.")

    print("Testing small collection fallback...")
    test_small_collection_single_topic_fallback(adapter)
    print("✓ Small collection fallback test passed.")

    print("Testing multi-cluster separation...")
    test_multi_cluster_c_tfidf_separation(adapter)
    print("✓ Multi-cluster separation test passed.")

    print("Testing knowledge gap detection...")
    test_knowledge_gap_detection(adapter)
    print("✓ Knowledge gap detection test passed.")

    print("\n🎉 All 4 Topic Clustering & Knowledge Gap tests passed successfully!")

