apiVersion: retriever.run/v1alpha1
kind: RetrieverCluster
metadata:
  name: retriever-dev
  namespace: default
spec:
  replicas: 1
  webReplicas: 0
  imageTag: "v1.2.0-alpha1"
  postgresPvcSize: "10Gi"
  gpu:
    enabled: false
  backupPolicy:
    enabled: false
